services:

  # MySQL 데이터베이스
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # 컨테이너가 꺼져도 DB 데이터 날아가면 안되니까 볼륨에 저장
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Spring Boot 백엔드
  backend:
    build: ./backend
    environment:
      DB_HOST: mysql    # IP주소 대신 컨테이너 이름으로 DB에 접근하는 모습
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql # 실행순서 !!!, mysql 컨테이너 먼저 뜬 다음에 backend 실행
    networks:
      - app-network

  # React 프론트엔드
  frontend:
    build: ./frontend
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - app-network

  # Prometheus - 메트릭 수집 및 저장
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network

  # Grafana - 시각화
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

  # Node Exporter - 호스트 OS 메트릭 수집
  node-exporter:
    image: prom/node-exporter
    networks:
      - app-network

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

networks:
  app-network: