worker_rlimit_nofile 8192;  # OS 파일 디스크립터 한도 올리기

events {
    worker_connections 4096;
}

http {
    server {
        listen 80;

        # / 로 오는 요청 → frontend 컨테이너로
        location / {
            proxy_pass http://frontend:80;
        }

        # /api 로 오는 요청 → backend 컨테이너로
        location /api {
            proxy_pass http://backend:8080;
        }
    }
}
